/**
 * ============================================================
 *  TYPES.TS — IqwanEngine Shared Type Definitions V5.0
 *  IqwanEngine | by Muhammad Hairul Iqwan
 * ============================================================
 */

/**
 * A single message node in the chat terminal.
 * Used by App.tsx state, localStorage serialization, and the chat renderer.
 */
export interface Message {
  /** Unique identifier — use Date.now().toString() for user messages */
  id: string;

  /** "user" = recruiter input | "ai" = IQWAN_ASSISTANT response */
  role: "user" | "ai";

  /**
   * The display text of the message.
   * For AI messages, may contain "[RESUME_BTN]" marker.
   * App.tsx parses this marker into a <a download> element.
   * ⚠️ Never render this via dangerouslySetInnerHTML — use textContent.
   */
  content: string;

  /** HH:MM display string generated by toLocaleTimeString */
  timestamp: string;

  /**
   * Optional instruction line shown above suggestion buttons.
   * Example: "You can type any random question below, or select a quick option:"
   */
  instruction?: string;

  /**
   * Quick-reply suggestion buttons rendered below this message.
   * Each string is sent verbatim to handleSendMessage() on click.
   * ⚠️ Must exactly match a `question` string in qaData for exact match to work.
   */
  suggestions?: string[];

  /**
   * Protocol status badge displayed on the message.
   * Example values: "SYNC_READY" | "PROCESSING"
   */
  status?: string;

  /** Thumbs up/down feedback state for this AI message */
  feedback?: "positive" | "negative";
}
